#!/bin/bash

cd ~/
git clone https://github.com/fireice-uk/xmr-stak.git
sudo apt-get update
sudo apt install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev
mkdir xmr-stak/build
cd xmr-stak/build
cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF
make install

cat > /tmp/cron << EOF
@reboot screen -d -m ~/xmr-stak/build/bin/xmr-stak -u $USERNAME -p $PASSWORD --url $URL --currency monero
EOF

crontab /tmp/cron

sudo shutdown -r now
